package org.helloworld.demo;

import javax.swing.*;
import java.awt.*;

public class MyForm {
    public JButton btn;
    public JPanel formPanel;

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
     * code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        formPanel = new JPanel();
        formPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        formPanel.add(panel1, BorderLayout.NORTH);
        btn = new JButton();
        btn.setText("Button");
        panel1.add(btn, BorderLayout.WEST);
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        formPanel.add(label1, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return formPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
